version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db-mysql
    restart: unless-stopped 
    environment:
      MYSQL_ROOT_PASSWORD: polpetta
      MYSQL_DATABASE: Users
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
 

volumes:
  dbdata:
